### PR TITLE
Applied a Laravel Telescope theme to the toolbar

### PR DESCRIPTION
**Pull request by GertjanRoke**
Hello,

I applied a Laravel Telescope theme to the toolbar, I thought it made sense because you use Telescope under the hood.

Hope you like it and if you any suggestions please let me know.

If you like it maybe you can make a new image for in the readme, I don’t have a big project running for all features at the moment.

Issue #5

### CODE REVIEW

**Comment by barryvdh** [comment]
Cool! Did you happen to have a screenshot?

**Comment by GertjanRoke** [comment]
Not at them moment, but I will make one later today when I have my hands free.

**Comment by GertjanRoke** [comment]
laravel-telescope-toolbar

@barryvdh this is what it looks like.

**Comment by barryvdh** [comment]
Looks nice! Made a tweak to the text and added a config option for light/dark mode on feat-layout.

**Comment by GertjanRoke** [comment]
Oh yeah! Good idea!

**Comment by barryvdh** [comment]
FYI, I've split everything between the original toolbar, global custom styling and specific theme colors, to make it a bit easier to follow (and perhaps upgrade / keep in sync).
Als tweaked the hover state a tiny bit:
image

I only feel that it might need some borders, especially on white background:

image


But I see that in your screenshot, so I might have missed something with merging.

**Comment by barryvdh** [comment]
nevermind, found it :)

**Comment by GertjanRoke** [comment]
Oh yeah, I placed a shadow around it.
Thought it made it look a bit softer.

**Comment by joowdx** [comment]
Nevermind. I created a pr here #56

**Pull request merged**
